-- Seed CV entries from static data
-- Run this AFTER cv_entries.sql migration

INSERT INTO cv_entries (section, year, title, subtitle, sort_order) VALUES

-- Education
('education', '2024', 'Advanced Stone Conservation Programme — UNESCO', NULL, 0),
('education', '2013', 'Certificate in Conservation of Cultural Property (Murals & Paintings)', NULL, 1),
('education', '2004', 'M.A. in Archaeology (studies commenced)', 'Postgraduate Institute of Archaeology, University of Kelaniya, Sri Lanka', 2),
('education', '2002', 'Postgraduate Diploma in Archaeology (Merit)', 'Postgraduate Institute of Archaeology, University of Kelaniya, Sri Lanka', 3),
('education', '2000', 'Bachelor of Fine Arts — BFA (Sculpture)', 'Institute of Aesthetic Studies, University of Kelaniya, Sri Lanka', 4),

-- Work Experience — Current
('work_current', 'Present', 'Vice Chairman / Founding Member', 'Theertha International Artists'' Collective & Red Dot Gallery, Colombo', 0),
('work_current', 'Present', 'Co-Founder & Director', 'Colombo Performance Art Platform (co-founded with Dr. G. R. Constantine)', 1),
('work_current', '2020–Present', 'Member — Colombo Resource Panel ''Our Stories'' Project', 'The Asia Foundation in collaboration with Theertha', 2),
('work_current', '2005–Present', 'Chief Coordinator — Travelling Art Education Exhibition', 'Theertha International Artists'' Collective (curated by Prof. Jagath Weerasinghe)', 3),
('work_current', '2015–present', 'Supervisor, undergraduate students on thesis related to performance art and visual art in Sri Lanka', NULL, 4),
('work_current', '2013–present', 'Lecturing in Museology, Diploma in Museology course', 'Postgraduate Institute of Archaeology, Colombo, Sri Lanka', 5),

-- Work Experience — Past
('work_past', '2010–2014', 'Research Administrator for Prof. Jagath Weerasinghe — Sethu Samuddram Community Art Project', 'Theertha International Artists Collective of Sri Lanka and 1ShanthiRoad artists'' organization, Bangalore, India', 0),
('work_past', '2010–2014', 'Chief Coordinator, Chief Project Manager and Training Instructor — Let''s Take a Walk Contemporary Art Project', 'Theertha International Artists'' Collective, Sri Lanka', 1),
('work_past', '2007–2013', 'Chief project manager and teacher training instructor — Art as a Third Channel project', 'In collaboration with Zonal Education Offices in Matara, Balangoda, Kandy, Akurassa', 2),
('work_past', '2007–2010', 'Chief Coordinator — "Ape Gam Palatha" (In Our Village Area) project', 'Theertha International Artists'' Collective, curated by Prof. Jagath Weerasinghe, Colombo, Sri Lanka', 3),
('work_past', '2007–2009', 'Consultant on stone carving and sculptures', 'Star Granite, Minuwangoda, Sri Lanka', 4),
('work_past', '2008', 'Consultant for wood carving workshop at Sigiriya Craft village, Sigiriya', 'Organized by National Craft Council', 5),
('work_past', '2007', 'Lecturer for 2nd year students — Modeling, casting and plaster carving', 'Plymouth College of Art and Design, UK', 6),
('work_past', '2006', 'Working committee member, Theertha International Artists'' Workshop – 2006', 'Kandy, Sri Lanka', 7),
('work_past', '2004', 'Coordinator, Jaffna Exhibition Project', 'Theertha International Artists'' Collective, Colombo, Sri Lanka', 8),
('work_past', '2003', 'Asst. Coordinator / Workshop Manager, Theertha International Artists'' Workshop 2003', 'Beruwala, Sri Lanka', 9),
('work_past', '2002–2003', 'Art teacher', 'Vidyarathana University College, Horana, Sri Lanka', 10),

-- Solo Exhibitions
('solo_exhibitions', '2026', '''Studio Finds: Rediscovered & Reimagined''', 'Art Rhizome, Colombo, Sri Lanka', 0),
('solo_exhibitions', '2009', '''Numbed''', 'Red Dot Gallery, Pitakotte, Sri Lanka', 1),

-- Group Exhibitions & Performances
('group_exhibitions', '2026', '''A Contemporary Convergence'' — Group Exhibition curated by Suresh Dominic', 'Curado Art Space, Colombo, Sri Lanka (19–31 March 2026)', 0),
('group_exhibitions', '2025', '''NOSTOS'' — Group Exhibition', 'The Barefoot Gallery, Colombo, Sri Lanka', 1),
('group_exhibitions', '2024–2025', '''Total Landscaping'' (Rotation 3)', 'Museum of Modern and Contemporary Art Sri Lanka (MMCA), Colombo. Public programming supported by Nations Trust Bank', 2),
('group_exhibitions', '2023', '''Antibodies'' — 24-hour Performance Marathon', 'HH Art Spaces & The Tetley, Leeds, supported by British Council; Aguada Central Jail, Goa, India (17–18 March 2023)', 3),
('group_exhibitions', '2022', '''The Smell'' — 4th Theertha Performance Platform', 'Theertha Red Dot Gallery, Sri Lanka', 4),
('group_exhibitions', '2022', '''The Black History'' — International Print Exhibition', 'Printmaking Gallery', 5),
('group_exhibitions', '2020', 'Iran-India 2020, ''Performance Art Project: Asia''', 'Rah Art Residence / hexxy duxxy box, via Zoom', 6),
('group_exhibitions', '2020', '''A Theertha Interim Show''', 'Theertha Red Dot Gallery, Borella, Colombo, Sri Lanka', 7),
('group_exhibitions', '2020', '''OBLAK Performances, Objects & Vulnerability'' — online via Zoom', 'Performed at Borella Junction', 8),
('group_exhibitions', '2019–2020', '''One Hundred Thousand Small Tales''', 'Museum of Modern and Contemporary Art Sri Lanka (MMCA), Colombo (Dec 2019 – Aug 2020)', 9),
('group_exhibitions', '2019', '''Texting Being'' — Theertha Performance Platform 2019', 'Theertha, Borella, Sri Lanka', 10),
('group_exhibitions', '2019', '''A Cross Section'' — Group Exhibition of Sri Lankan Artists', 'Jaleh Gallery, Tehran, Iran', 11),
('group_exhibitions', '2019', '''Contemporary Sri Lankan Art: A Cross-Section''', 'Iranian Cultural Centre, Colombo, Sri Lanka', 12),
('group_exhibitions', '2018', '''One Hundred Thousand Small Tales'' — 4th Dhaka Art Summit', 'Bangladesh Shilpakala Academy, Dhaka, Bangladesh (curated by Sharmini Pereira, organised by Samdani Art Foundation)', 13),
('group_exhibitions', '2017', '''A Tale of Two Cities | India and Sri Lanka''', 'Theertha Red Dot Gallery, Colombo, Sri Lanka', 14),
('group_exhibitions', '2017', 'ART CONNECT — Colombo Fashion Week 2017', 'Colombo, Sri Lanka', 15),
('group_exhibitions', '2017', '''Portraits of Intervention: Contemporary Art from Sri Lanka''', 'Aicon Gallery, New York, USA', 16),
('group_exhibitions', '2017', '''Life and Time — The Changing Landscape''', 'Academy of Fine Arts, Kolkata, India', 17),
('group_exhibitions', '2017', 'Theertha Performance Platform', 'Theertha Red Dot Gallery, Borella, Colombo, Sri Lanka', 18),
('group_exhibitions', '2017', '''A Tale of Two Cities | India and Sri Lanka''', 'IGNCA, New Delhi, India', 19),
('group_exhibitions', '2016', '''A Tale of Two Cities | India and Sri Lanka''', 'Serendipity Arts Festival, Adil Shah Palace, Goa, India', 20),
('group_exhibitions', '2016', '''Washing Man'' — performance, OPEN 6, curated by Nikhil Chopra', 'Open Studio Residency, The Heritage Hotel: Art Spaces, Goa, India', 21),
('group_exhibitions', '2016', '''Iron Man'' — performance', 'India Art Fair, New Delhi, India', 22),
('group_exhibitions', '2016', '''Reading The Biography'' — performance with G.R. Constantine', 'Theertha Performance Evening, Colombo, Sri Lanka', 23),
('group_exhibitions', '2016', '''Developing Land'' — performance', 'Theertha Performance Evening, Colombo, Sri Lanka', 24),
('group_exhibitions', '2016', '''Washing Man'' — performance, Down Town Pulse 2016', 'Bakeriya Space, Colombo', 25),
('group_exhibitions', '2015', '''Dead Fish'' — performance', 'Theertha Performance Platform 1st Edition, Sri Lanka', 26),
('group_exhibitions', '2014', '''Me and My Image'' — performance with Godwin Constantine', '''Transforming Bodies'', Colombo Dance Platform 2014', 27),
('group_exhibitions', '2014', '''Serendipity Revealed: An Exhibition of Contemporary Sri Lankan Art''', 'Brunei Gallery, SOAS, London, UK', 28),
('group_exhibitions', '2014', '''Beware Wet Ink'' — Digital Art Exhibition', 'Lionel Wendt Gallery, Colombo', 29),
('group_exhibitions', '2014', 'Dhaka Art Summit', 'Dhaka, Bangladesh', 30),
('group_exhibitions', '2014', '''Making History'' — Colombo Art Biennale, curated by Amit Jain', NULL, 31),
('group_exhibitions', '2013', '''Golden Barrel Man'' (2nd performance) — ''WAR & PEACE: Visual Narratives from Contemporary Sri Lanka''', 'Harold Pieris Gallery, Colombo', 32),
('group_exhibitions', '2012', '''Becoming'' — 2nd Colombo Art Biennale, curated by Suresh Jayaram & Roman Berka', NULL, 33),
('group_exhibitions', '2011', '''Crushing Eggs'' — Live Art 2011', 'Bangalore Artists'' Residency, India', 34),
('group_exhibitions', '2011', 'Sethu Residency 2 Exhibition', 'Theertha Red Dot Gallery, Colombo, Sri Lanka', 35),
('group_exhibitions', '2011', '''Beyond Pressure'' Performance Art Festival', 'Myanmar', 36),
('group_exhibitions', '2011', '''(de)-inscribed Memories'' — Group Exhibition with Pradeep Chandrasiri', 'Hempel Galleries, Colombo', 37),
('group_exhibitions', '2011', 'Theertha @ 1.Shanthi Road', 'Bangalore, India', 38),
('group_exhibitions', '2011', 'Sethu Residency 1 — Shanthi Road @ Theertha 2010', 'Red Dot Gallery, Colombo', 39),
('group_exhibitions', '2009', '''Imagining Peace'' — 1st Colombo Art Biennale', 'Curated by Prof. Jagath Weerasinghe & Annoushka Hampel, Sri Lanka', 40),
('group_exhibitions', '2009', '''Theertha — Works on Paper''', 'National Art Gallery, Maldives', 41),
('group_exhibitions', '2009', '''PostcART''', 'Sudu Gallery, Galle, Sri Lanka', 42),
('group_exhibitions', '2008', 'International Artists'' Residency Exhibition', 'Red Dot Gallery, Pitakotte, Sri Lanka', 43),
('group_exhibitions', '2008', '''Artful Resistance''', 'Museum of Anthropology, Vienna, Austria', 44),
('group_exhibitions', '2007', '''Buy 1 Get 1 Free'' — HAT2 Programme', 'Plymouth College of Art and Design Gallery, UK', 45),
('group_exhibitions', '2006', '''The Maze'' — Collaborative Art Project', 'Lionel Wendt Gallery, Colombo, Sri Lanka', 46),
('group_exhibitions', '2005', '''Contemporary Sri Lankan Art''', 'Museum of Far Eastern Antiquities, Stockholm, Sweden', 47),
('group_exhibitions', '2005', '''Urban and the Individual''', 'Fenominal Art Gallery, Colombo, Sri Lanka', 48),
('group_exhibitions', '2005', '''Aham Puram''', 'Theertha International Artists'' Collective, Public Library, Jaffna, Sri Lanka', 49),
('group_exhibitions', '2004', '''Exhibition of Paintings and Sculpture''', 'Gallery 71, Galle Fort, Galle, Sri Lanka', 50),
('group_exhibitions', '2003', '''2nd Theertha International Artists'' Workshop'' Exhibition', 'Lunuganga Gardens, Beruwala, Sri Lanka', 51),
('group_exhibitions', '2003', '''Chartered Theft''', 'VAFA Gallery, Ethul Kotte, Sri Lanka', 52),
('group_exhibitions', '2002', '''Crafty Thoughts''', 'University of Liverpool Art Gallery, Liverpool, UK', 53),
('group_exhibitions', '2001', '1st Theertha International Artists'' Workshop', 'Gallery 706, Colombo, Sri Lanka', 54),
('group_exhibitions', '2000', '4th Art Link International Artists'' Workshop', 'Gallery 706, Colombo, Sri Lanka', 55),
('group_exhibitions', '2000', '''An Art Exhibition for Peace and Reconciliation''', 'Gallery 706, Colombo, Sri Lanka', 56),
('group_exhibitions', '2000', '''Made in IAS''', 'Gallery 706, Colombo, Sri Lanka', 57),
('group_exhibitions', '2000', '''Artist for Peace'' — Flag Exhibition', 'Selected Public Places, Sri Lanka', 58),
('group_exhibitions', '1999', '''State Art Festival''', 'National Art Gallery, Colombo, Sri Lanka', 59),
('group_exhibitions', '1999', '''Young Contemporaries''', 'National Art Gallery, Colombo, Sri Lanka', 60),
('group_exhibitions', '1999', '''Nawa Kalakaruwo''', 'National Art Gallery, Colombo, Sri Lanka', 61),
('group_exhibitions', '1999', '''The Sculpture of Contemporary Sri Lanka''', 'National Art Gallery, Colombo, Sri Lanka', 62),
('group_exhibitions', '1998', '''New Directions''', 'Mount Castle Gallery, Colombo, Sri Lanka', 63),
('group_exhibitions', '1998', '''Modern Painting, Sculpture and Installation''', 'Mahanaga Mandiraya, Humbantota, Sri Lanka', 64),

-- Workshops & Residencies
('workshops_residencies', '2025', 'Museum Intensive 3 (MI 3) — Integrated Pest Management & Archival Conservation Workshop', 'MMCA Sri Lanka, Colombo (10–11 March 2025). Conducted by Nicola Walker, Senior Conservator, National Trust UK; developed in partnership with World Monuments Fund', 0),
('workshops_residencies', '2023', 'Artist Delegate & Collaborator — 7th Arts Collaboratory Assembly', 'Netherlands (Utrecht, Amsterdam, Eindhoven). Represented Theertha International Artists'' Collective', 1),
('workshops_residencies', '2019', 'Artist in Residence — Theertha', 'Colombo, Sri Lanka', 2),
('workshops_residencies', '2017', 'Venice International Performance Art Week', 'Venice, Italy', 3),
('workshops_residencies', '2016', 'Falls Creek Artist Camp', 'Melbourne, Australia', 4),
('workshops_residencies', '2016', 'David Thomas Art Space', 'Melbourne, Australia', 5),
('workshops_residencies', '2016', 'OPEN 6, Open Studio Residency', 'The Heritage Hotel: Art Spaces, Goa, India', 6),
('workshops_residencies', '2015–ongoing', 'Participant — The Tale of Two Cities 2015', 'One-year-long project for established artists of India and Sri Lanka, exploring Varanasi and Anuradhapura. Conceived by Renu Modi; sponsored by Espace Gallery, Theertha International Artists Collective and Serendipity Arts Trust', 7),
('workshops_residencies', '2015', 'Art Collaboratory Institutional Residency', 'Kunchi Cultural Studies Center, Yogyakarta, Indonesia', 8),
('workshops_residencies', '2011', 'Workshop in Art History: Buddhist Iconography — conducted by Dr. Nandana Chutiwongs', 'Postgraduate Institute of Archaeology (PGIAR), University of Kelaniya, Colombo', 9),
('workshops_residencies', '2011', 'Workshop in Art History: Sri Lanka and Burma in the wider Buddhist world — conducted by Dr. Donald Stadner', 'Former Associate Professor, University of Texas, Austin', 10),
('workshops_residencies', '2010', '3rd Beyond Pressure Festival of Performance Art', 'Myanmar', 11),
('workshops_residencies', '2010', 'Theertha International Artists'' Workshop', 'Colombo, Sri Lanka', 12),
('workshops_residencies', '2008', 'Landscape Drawing Workshop', 'Theertha International Artists'' Collective Studio, Colombo', 13),
('workshops_residencies', '2008', 'International Artists'' Residency', 'Theertha International Artists'' Collective, Pitakotte, Sri Lanka', 14),
('workshops_residencies', '2007', 'Crafting the Drawing and Drawing the Craft', 'Theertha International Artists'' Collective Studio, Colombo', 15),
('workshops_residencies', '2007', 'CHAT Week (HAT2 Programme)', 'Sanskriti Kendra, New Delhi, India', 16),
('workshops_residencies', '2007', 'HAT2 Programme: International Research Fellowship — Three months Residency', 'Plymouth College of Art and Design, UK', 17),
('workshops_residencies', '2007', 'Paper Casting Workshop', 'Sanskriti Kendra, New Delhi, India', 18),
('workshops_residencies', '2003', 'Burragorang International Artists'' Workshop', 'New South Wales, Australia', 19),
('workshops_residencies', '2003', 'Art and Craft Workshop at Polonnaruwa', 'ArtLab, Colombo, Sri Lanka', 20),
('workshops_residencies', '2002', 'Peace Train Project', 'Vibavi Academy of Fine Arts, Ethulkotte, Sri Lanka', 21),
('workshops_residencies', '2001', '1st Theertha International Artists'' Workshop', 'Beruwala, Sri Lanka', 22),
('workshops_residencies', '2000', 'Art Link — 4th International Artists'' Camp', 'Culture Club, Kandalama, Sri Lanka', 23),
('workshops_residencies', '2000', 'Artists for Peace (Street Flag Painting Project)', 'Fort Railway Station, Colombo, Sri Lanka', 24),
('workshops_residencies', '2000', 'Workshop with Sue Pedley', 'Lunuganga Gardens, Beruwala, Sri Lanka', 25),
('workshops_residencies', '1999', 'Workshop with Fiona Hall', 'Lunuganga Gardens, Beruwala, Sri Lanka', 26),

-- Invited Lectures & Talks
('invited_lectures', '2015', 'Lecture and presentation on Performance Art and Photo Performance', 'City School of Architecture (partnering with University of the West of England, Bristol, UK) — for 1st year students', 0),
('invited_lectures', '2013', 'Talk on "Golden Barrel Man – Performance artwork by Bandu Manamperi"', 'WAR & PEACE – Visual Narratives from contemporary Sri Lanka, Harold Pieris Gallery, Colombo, Sri Lanka', 1),
('invited_lectures', '2011', 'Lecture on "The body as Language"', 'Post Graduate Institute of Archaeology (PGIAR), Colombo, Sri Lanka', 2),
('invited_lectures', '2010', 'Lecture on "Sri Lankan Performance Art"', 'German Culture Centre, Colombo — organized by Theertha International Artists'' Collective, Pitakotte, Sri Lanka', 3),
('invited_lectures', '2010', 'Symposium on "Sri Lanka Performance Art"', '3rd Beyond Pressure Festival of Performance Art, Myanmar — Kargqwell Co-YIN KABAR Gallery', 4);
